version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage

  airflow:
    image: apache/airflow:2.9.1
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8081:8080"
    command: airflow standalone
    networks:
      - data_network
    env_file:
      - .env 
networks:
  data_network:
    driver: bridge
    name: data_networ
